In [1]:
import sym
import numpy as np

In [6]:
sym.__rot_90_180_270__([1,0,0])

array([[ 6.1232340e-17,  1.0000000e+00,  0.0000000e+00],
       [-1.0000000e+00,  1.2246468e-16,  0.0000000e+00],
       [-1.8369702e-16, -1.0000000e+00,  0.0000000e+00]])

In [8]:
help(sym)

Help on module sym:

NAME
    sym

DESCRIPTION
    General crystallographic symmetry operators
    Cubic and hexagonal operators are available.
    
    
    -- List of symmery operators
    def cubic()
    def hexag()
    def tetra()
    def triclinic()

FUNCTIONS
    __60_120_rot111__(h)
        For the given h operation,
        rotations of (pi/3) & (2*pi/3) around <111>
        are performed and returned
        
        *cubic
    
    __mirror_110__(h)
        Given the operation h, mirrored across the (110) plane returned
        
        *cubic
    
    __mmm__()
    
    __nomem__()
    
    __rot_90_180_270__(h)
        Given the operation h,
        the three rotated operations are returned
        
        *cubic
    
    __rot_nrot_001__(h, csym=None)
        Rotations of 2*pi/nrot around axis <001>
        
        *hexagoanl, trigonal, tetragonal
        
        ---------
        Arguments
        h: symmetry operators
        csym: 'hexa'
    
    __rot_nrot_x1__(h, n

In [4]:
cubic = sym.cubic()
print(cubic)
# sym.cubic_centro()
# sym.hexag()
# sym.cubic()

[[[ 1.  0.  0.]
  [ 0.  1.  0.]
  [ 0.  0.  1.]]

 [[ 0.  0.  1.]
  [ 1.  0.  0.]
  [ 0.  1.  0.]]

 [[ 0.  1.  0.]
  [ 0.  0.  1.]
  [ 1.  0.  0.]]

 [[ 0.  1.  0.]
  [ 1.  0.  0.]
  [ 0.  0.  1.]]

 [[ 1.  0.  0.]
  [ 0.  0.  1.]
  [ 0.  1.  0.]]

 [[ 0.  0.  1.]
  [ 0.  1.  0.]
  [ 1.  0.  0.]]

 [[ 0. -1.  0.]
  [ 1.  0.  0.]
  [ 0.  0.  1.]]

 [[-1.  0.  0.]
  [ 0. -1.  0.]
  [ 0.  0.  1.]]

 [[ 0.  1.  0.]
  [-1.  0.  0.]
  [ 0.  0.  1.]]

 [[-1.  0.  0.]
  [ 0.  0.  1.]
  [ 0.  1.  0.]]

 [[ 0.  0. -1.]
  [-1.  0.  0.]
  [ 0.  1.  0.]]

 [[ 1.  0.  0.]
  [ 0.  0. -1.]
  [ 0.  1.  0.]]

 [[ 0.  0. -1.]
  [ 0.  1.  0.]
  [ 1.  0.  0.]]

 [[ 0. -1.  0.]
  [ 0.  0. -1.]
  [ 1.  0.  0.]]

 [[ 0.  0.  1.]
  [ 0. -1.  0.]
  [ 1.  0.  0.]]

 [[-1.  0.  0.]
  [ 0.  1.  0.]
  [ 0.  0.  1.]]

 [[ 0. -1.  0.]
  [-1.  0.  0.]
  [ 0.  0.  1.]]

 [[ 1.  0.  0.]
  [ 0. -1.  0.]
  [ 0.  0.  1.]]

 [[ 0.  0. -1.]
  [ 1.  0.  0.]
  [ 0.  1.  0.]]

 [[-1.  0.  0.]
  [ 0.  0. -1.]
  [ 0.  1.  0.]]



In [35]:
for i in range(len(cubic)):
    print(f'cubic[{i}] = {cubic[i]}', np.dot(cubic[i], [1,1,1]))

cubic[0] = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [1. 1. 1.]
cubic[1] = [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] [1. 1. 1.]
cubic[2] = [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] [1. 1. 1.]
cubic[3] = [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]] [1. 1. 1.]
cubic[4] = [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]] [1. 1. 1.]
cubic[5] = [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] [1. 1. 1.]
cubic[6] = [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]] [-1.  1.  1.]
cubic[7] = [[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]] [-1. -1.  1.]
cubic[8] = [[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]] [ 1. -1.  1.]
cubic[9] = [[-1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]] [-1.  1.  1.]
cubic[10] = [[ 0.  0. -1.]
 [-1.  0.  0.]
 [ 0.  1.  0.]] [-1. -1.  1.]
cubic[11] = [[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]] [ 1. -1.  1.]
cubic[12] = [[ 0.  0. -1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]] [-1.  1.  1.]
cubic[13] = [[ 0. -1.  0.]
 [ 0.  0. -1.]
 [ 1.  0.  0.]] [-1. -1.  1.]
cubic[14] = [[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 1.  0.  0.]] [ 1. -1.  1.]
cu