In [33]:
import sym
import numpy as np

In [6]:
sym.__rot_90_180_270__([1,0,0])

array([[ 6.1232340e-17,  1.0000000e+00,  0.0000000e+00],
       [-1.0000000e+00,  1.2246468e-16,  0.0000000e+00],
       [-1.8369702e-16, -1.0000000e+00,  0.0000000e+00]])

In [8]:
help(sym)

Help on module sym:

NAME
    sym

DESCRIPTION
    General crystallographic symmetry operators
    Cubic and hexagonal operators are available.
    
    
    -- List of symmery operators
    def cubic()
    def hexag()
    def tetra()
    def triclinic()

FUNCTIONS
    __60_120_rot111__(h)
        For the given h operation,
        rotations of (pi/3) & (2*pi/3) around <111>
        are performed and returned
        
        *cubic
    
    __mirror_110__(h)
        Given the operation h, mirrored across the (110) plane returned
        
        *cubic
    
    __mmm__()
    
    __nomem__()
    
    __rot_90_180_270__(h)
        Given the operation h,
        the three rotated operations are returned
        
        *cubic
    
    __rot_nrot_001__(h, csym=None)
        Rotations of 2*pi/nrot around axis <001>
        
        *hexagoanl, trigonal, tetragonal
        
        ---------
        Arguments
        h: symmetry operators
        csym: 'hexa'
    
    __rot_nrot_x1__(h, n

In [27]:
cubic = sym.cubic()
# print(cubic)
# sym.cubic_centro()
# sym.hexag()
# sym.cubic()

In [28]:
for i in range(len(cubic)):
    print(f'cubic[{i}] = {cubic[i]}', np.dot(cubic[i], [1,1,1]))

cubic[0] = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [1. 1. 1.]
cubic[1] = [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] [1. 1. 1.]
cubic[2] = [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] [1. 1. 1.]
cubic[3] = [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]] [1. 1. 1.]
cubic[4] = [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]] [1. 1. 1.]
cubic[5] = [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] [1. 1. 1.]
cubic[6] = [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]] [-1.  1.  1.]
cubic[7] = [[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]] [-1. -1.  1.]
cubic[8] = [[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]] [ 1. -1.  1.]
cubic[9] = [[-1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]] [-1.  1.  1.]
cubic[10] = [[ 0.  0. -1.]
 [-1.  0.  0.]
 [ 0.  1.  0.]] [-1. -1.  1.]
cubic[11] = [[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]] [ 1. -1.  1.]
cubic[12] = [[ 0.  0. -1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]] [-1.  1.  1.]
cubic[13] = [[ 0. -1.  0.]
 [ 0.  0. -1.]
 [ 1.  0.  0.]] [-1. -1.  1.]
cubic[14] = [[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 1.  0.  0.]] [ 1. -1.  1.]
cu

In [29]:
ang = np.pi/2.
print(np.cos(ang))
print(np.cos(1.57))
print(np.cos(np.pi))

6.123233995736766e-17
0.0007963267107332633
-1.0


In [23]:
sym.cubic_centro()

[array([[-1.,  0.,  0.],
        [ 0., -1.,  0.],
        [ 0.,  0., -1.]]),
 array([[ 0.,  0., -1.],
        [-1.,  0.,  0.],
        [ 0., -1.,  0.]]),
 array([[ 0., -1.,  0.],
        [ 0.,  0., -1.],
        [-1.,  0.,  0.]]),
 array([[ 0., -1.,  0.],
        [-1.,  0.,  0.],
        [ 0.,  0., -1.]]),
 array([[-1.,  0.,  0.],
        [ 0.,  0., -1.],
        [ 0., -1.,  0.]]),
 array([[ 0.,  0., -1.],
        [ 0., -1.,  0.],
        [-1.,  0.,  0.]]),
 array([[ 0.,  1.,  0.],
        [-1.,  0.,  0.],
        [ 0.,  0., -1.]]),
 array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0., -1.]]),
 array([[ 0., -1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0., -1.]]),
 array([[ 1.,  0.,  0.],
        [ 0.,  0., -1.],
        [ 0., -1.,  0.]]),
 array([[ 0.,  0.,  1.],
        [ 1.,  0.,  0.],
        [ 0., -1.,  0.]]),
 array([[-1.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 0., -1.,  0.]]),
 array([[ 0.,  0.,  1.],
        [ 0., -1.,  0.],
        [-1.,  0.,  0.]]),

In [10]:
h_n = [[-1,1,7],[1,-1,-21],[2,1,-1]]
tempDot = [[-1,3,2],[2,-1,4],[3,2,-1]]
print("dot", np.dot(h_n, tempDot),"\n\n")
print("* = ", np.array(h_n) * np.array(tempDot))


dot [[ 24  10  -5]
 [-66 -38  19]
 [ -3   3   9]] 


* =  [[  1   3  14]
 [  2   1 -84]
 [  6   2   1]]


In [25]:
np.dot([2,1],[3,7])

13

In [6]:
temp1 = np.array([2,1])
temp2 = np.array([3,7])
print(temp1 * temp2)

[6 7]


In [27]:
sym.triclinic()

[array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])]

In [23]:
temp = np.zeros((3,1))
for i

array([[0.],
       [0.],
       [0.]])

In [37]:
cubic_miller_idx = [[(0,0,1), (1,0,0), (0,1,0), (1,0,1), (1,1,0), (0,1,1), (1,1,1), (1,-1,1), (-1,1,1)]]
print(len(cubic_miller_idx))

1


In [38]:
len(sym.hexag())

12